//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp9.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mark
    {
        public int idMark { get; set; }
        public int idstudent { get; set; }
        public int id_lesson { get; set; }
        public System.DateTime completion_date { get; set; }
        public int Grade { get; set; }
        public int kode_lesson { get; set; }
    
        public virtual lesson lesson { get; set; }
        public virtual student student { get; set; }
    }
}
