//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp9.db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class base08Entities : DbContext
    {
        public base08Entities()
            : base("name=base08Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<lesson> lesson { get; set; }
        public virtual DbSet<Mark> Mark { get; set; }
        public virtual DbSet<student> student { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<teacher> teacher { get; set; }
        public virtual DbSet<группа> группа { get; set; }
        public virtual DbSet<журнал> журнал { get; set; }
        public virtual DbSet<предмет> предмет { get; set; }
        public virtual DbSet<расписание> расписание { get; set; }
    }
}
