//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp9.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class журнал
    {
        public int idstudent { get; set; }
        public string расписание { get; set; }
        public int оценка { get; set; }
    
        public virtual student student { get; set; }
    }
}
