//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp9.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class расписание
    {
        public int id_group { get; set; }
        public System.DateTime data { get; set; }
        public int id_predmeta { get; set; }
        public int id_lesson { get; set; }
        public System.DateTime kabinet { get; set; }
        public string журнал { get; set; }
    
        public virtual lesson lesson { get; set; }
        public virtual student student { get; set; }
        public virtual предмет предмет { get; set; }
    }
}
